[features]
seeds = false
skip-lint = false
[programs.localnet]
diamondhanding_solana_program = "5Zm2UQMSM63NLJGkQYP6xqqGm2EPzYyVNtyPpJnJb5iD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shellsnail/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
